# Generated by Django 6.0.1 on 2026-01-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0002_category_menuitem_order_cart_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="qunatity",
            new_name="quantity",
        ),
    ]
