# Generated by Django 6.0.1 on 2026-01-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0003_rename_qunatity_cart_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="satus",
            new_name="status",
        ),
    ]
